# On-chain parameters
margin_type = "Cross"
maturity = "Mar 27 2026 00:00 UTC"

[Margin]
kIM = 1/1.1
kMM = 2/3
I_threshold = 0.04
t_threshold = "7 days"
critical_health_ratio = 0.4
no_order_health_ratio = 0.95

[OrderBounds]
k_MD = 0.15
k_CO = 0.1
limit_Order_Upper_Slope = 1.05 
limit_Order_Lower_Slope = 0.95 

[MitigatingMeasure]
# Initial, 1-sided, in USD
hard_OI_cap = $20M

[Oracle]
mark_rate_twap_duration = "5 min"

[AMM]
fee_rate = 0%
initial_supply_cap_usd = $15k
oracle_twap_duration = "1 min"
min_rate = 0.02
max_rate = 0.5
initial_rate = 0.06
initial_size = 0.49784940
flip_liquidity = 0.40276863
initial_cash = 0.03096002

## Off-chain parameters

[AutomaticResponses]
new_liquidation_incentive_base = 0.5 
new_liquidation_incentive_slope = 0 
new_k_MD = 0.1
new_k_CO = 0.06
new_limit_Order_Upper_Slope = 1.025
new_limit_Order_Lower_Slope = 0.975