# On-chain parameters
margin_type = "Isolated"
maturity = "Mar 27 2026 00:00 UTC"

[Margin]
kIM = 1/1.1
kMM = 2/3
I_threshold = 0.4
t_threshold = "10 days"
critical_health_ratio = 0.4
no_order_health_ratio = 0.95

[OrderBounds]
k_MD = 0.3
k_CO = 0.1
limit_Order_Upper_Slope = 1.1 
limit_Order_Lower_Slope = 0.9 

[MitigatingMeasure]
# Initial, 1-sided, in USD
hard_OI_cap = $20M

[Oracle]
mark_rate_twap_duration = "5 min"

[AMM]
fee_rate = 0%
initial_supply_cap_usd = $15k
oracle_twap_duration = "1 min"
min_rate = 0.07
max_rate = 2
initial_rate = 0.3
initial_size = 2,898.05049798
flip_liquidity = 1,831.90318378
initial_cash = 1,930.92317991

## Off-chain parameters

[AutomaticResponses]
new_liquidation_incentive_base = 0.5 
new_liquidation_incentive_slope = 0 
new_k_MD = 0.1
new_k_CO = 0.06
new_limit_Order_Upper_Slope = 1.05
new_limit_Order_Lower_Slope = 0.95